# Generated by Django 4.2.10 on 2024-03-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children_name', models.CharField(max_length=255)),
                ('rfid_tag', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'children_tbl',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('get_same_video', models.BooleanField(default=False)),
                ('appears_in_others_video', models.BooleanField(default=False)),
                ('voice_can_be_recorded', models.BooleanField(default=False)),
                ('be_shown_potential', models.BooleanField(default=False)),
                ('be_shown_public_business', models.BooleanField(default=False)),
                ('be_shown_social_media', models.BooleanField(default=False)),
                ('paid_status', models.BooleanField(default=False)),
                ('rfid_tag', models.CharField(max_length=255)),
                ('tour_status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_tbl',
            },
        ),
    ]
