# Generated by Django 4.2.10 on 2024-03-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('children_name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'children_tbl',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('get_same_video', models.BooleanField(default=False)),
                ('appears_in_other_video', models.BooleanField(default=False)),
                ('voice_can_be_recorded', models.BooleanField(default=False)),
                ('be_shown_potential', models.BooleanField(default=False)),
                ('be_shown_public_business', models.BooleanField(default=False)),
                ('be_shown_social_media', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_tbl',
            },
        ),
        migrations.CreateModel(
            name='FacialPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_key', models.IntegerField()),
                ('img_url', models.ImageField(upload_to='facial_pictures/')),
                ('client_id', models.IntegerField()),
                ('face_type', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'facial_pictures_tbl',
            },
        ),
    ]
