# Generated by Django 4.2.10 on 2024-03-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildFacialPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_key', models.IntegerField()),
                ('img_url', models.ImageField(upload_to='facial_pictures/')),
                ('face_type', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.children')),
            ],
            options={
                'db_table': 'children_facial_pictures_tbl',
            },
        ),
        migrations.CreateModel(
            name='ClientFacialPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_key', models.IntegerField()),
                ('img_url', models.ImageField(upload_to='facial_pictures/')),
                ('face_type', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.client')),
            ],
            options={
                'db_table': 'client_facial_pictures_tbl',
            },
        ),
        migrations.DeleteModel(
            name='FacialPictures',
        ),
    ]
