# Generated by Django 4.2.10 on 2024-03-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='appears_in_other_video',
            new_name='appears_in_others_video',
        ),
    ]
